/* Plain JavaScript frontend for the existing FastAPI API. Set API_BASE if the UI is hosted separately. */
const API_BASE = 'http://localhost:8000';
const $ = (id) => document.getElementById(id);
const state = { records: [], selectedKey: '', chart: null, history: [], jobPollTimer: null };
const KPI_FIELDS = [
  { key: 'revenue', label: 'Revenue' },
  { key: 'net_income', label: 'Net income' },
  { key: 'operating_income', label: 'Operating income' },
  { key: 'cash_flow', label: 'Operating cash flow', aliases: ['operating_cash_flow', 'cash_flow_from_operating_activities'] },
  { key: 'total_assets', label: 'Total assets' },
  { key: 'total_liabilities', label: 'Total liabilities' }
];
function first(record, keys) { for (const key of keys) if (record && record[key] !== undefined && record[key] !== null) return record[key]; return ''; }
function valueFor(record, field) { return first(record, [field.key, ...(field.aliases || []), field.label, field.label.toLowerCase().replaceAll(' ', '_')]); }
function companyOf(r) { return String(first(r, ['company', 'company_name']) || 'Unknown company'); }
function yearOf(r) { return String(first(r, ['year', 'fiscal_year']) || ''); }
function keyOf(r) { return `${companyOf(r)}::${yearOf(r)}`; }
function textValue(value) { if (value === null || value === undefined || value === '') return '—'; if (Array.isArray(value)) return value.join(', '); if (typeof value === 'object') return JSON.stringify(value); return String(value); }
function escapeHtml(s) { return String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); }
function showToast(message, type = '') { const toast = document.createElement('div'); toast.className = `toast ${type}`; toast.textContent = message; $('toastContainer').appendChild(toast); setTimeout(() => toast.remove(), 4800); }
async function api(path, options = {}) { const response = await fetch(`${API_BASE}${path}`, options); const raw = await response.text(); let data = null; try { data = raw ? JSON.parse(raw) : null; } catch { data = raw; } if (!response.ok) { const detail = data && typeof data === 'object' ? (data.detail || data.message) : data; throw new Error(detail || `Request failed (${response.status})`); } return data; }
function setApiStatus(online, label) { $('apiStatus').textContent = label; const dot = document.querySelector('.connection-card .status-dot'); dot.style.background = online ? '#16b887' : '#d94d61'; }
async function checkHealth() { try { await api('/health'); setApiStatus(true, 'Connected to FastAPI'); } catch { setApiStatus(false, 'Backend unavailable'); } }
function reportLabel(r) { return `${companyOf(r)}${yearOf(r) ? ` (${yearOf(r)})` : ''}`; }
function renderSelectors() {
  const reports = [...state.records].sort((a, b) => companyOf(a).localeCompare(companyOf(b)) || yearOf(b).localeCompare(yearOf(a)));
  const currentReport = $('reportSelect').value; const currentInsight = $('insightSelect').value;
  $('reportSelect').innerHTML = '<option value="">All reports</option>' + reports.map(r => `<option value="${escapeHtml(keyOf(r))}">${escapeHtml(reportLabel(r))}</option>`).join('');
  $('insightSelect').innerHTML = '<option value="">Select a report</option>' + reports.map(r => `<option value="${escapeHtml(keyOf(r))}">${escapeHtml(reportLabel(r))}</option>`).join('');
  if (reports.some(r => keyOf(r) === currentReport)) $('reportSelect').value = currentReport;
  if (reports.some(r => keyOf(r) === currentInsight)) $('insightSelect').value = currentInsight;
  const companies = [...new Set(reports.map(companyOf))].sort();
  $('chatCompanySelect').innerHTML = '<option value="">All companies</option>' + companies.map(c => `<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join('');
  const years = [...new Set(reports.map(yearOf).filter(Boolean))].sort((a, b) => b.localeCompare(a));
  $('chatYearSelect').innerHTML = '<option value="">All years</option>' + years.map(y => `<option value="${escapeHtml(y)}">${escapeHtml(y)}</option>`).join('');
}
function renderStats() {
  const companies = new Set(state.records.map(companyOf)); const years = state.records.map(yearOf).filter(Boolean).sort((a, b) => b.localeCompare(a));
  $('statsCompanies').textContent = companies.size; $('statsReports').textContent = state.records.length;
  $('statsRevenue').textContent = state.records.filter(r => valueFor(r, KPI_FIELDS[0]) !== '').length;
  $('statsYear').textContent = years[0] || '—'; $('lastUpdated').textContent = `Updated ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;
}
function renderTable() {
  const q = $('tableSearch').value.trim().toLowerCase(); const rows = state.records.filter(r => `${companyOf(r)} ${yearOf(r)}`.toLowerCase().includes(q));
  $('recordCount').textContent = `${rows.length} record${rows.length === 1 ? '' : 's'}`;
  if (!rows.length) { $('metricsTableBody').innerHTML = `<tr><td colspan="7" class="table-empty">${state.records.length ? 'No reports match your search.' : 'No KPI records yet. Ingest a PDF to get started.'}</td></tr>`; return; }
  $('metricsTableBody').innerHTML = rows.map(r => `<tr><td><div class="company-cell"><span class="company-avatar">${escapeHtml(companyOf(r).slice(0, 2).toUpperCase())}</span><span>${escapeHtml(companyOf(r))}<br><small style="font-weight:500;color:#98a2b4">${escapeHtml(yearOf(r))}</small></span></div></td>${KPI_FIELDS.map(f => `<td>${escapeHtml(textValue(valueFor(r, f)))}</td>`).join('')}</tr>`).join('');
}
function numericMetric(v) { if (typeof v === 'number') return v; const s = String(v ?? '').replace(/,/g, '').replace(/[$₹€£%\s]/g, ''); const n = Number(s); return Number.isFinite(n) ? n : null; }
function renderChart() {
  const selected = $('reportSelect').value; const rows = state.records.filter(r => !selected || keyOf(r) === selected);
  const labels = rows.map(reportLabel); const datasets = [
    { label: 'Revenue', data: rows.map(r => numericMetric(valueFor(r, KPI_FIELDS[0]))), backgroundColor: '#3867f4', borderRadius: 5 },
    { label: 'Net income', data: rows.map(r => numericMetric(valueFor(r, KPI_FIELDS[1]))), backgroundColor: '#8064e8', borderRadius: 5 },
    { label: 'Operating income', data: rows.map(r => numericMetric(valueFor(r, KPI_FIELDS[2]))), backgroundColor: '#159c75', borderRadius: 5 }
  ];
  const hasValues = datasets.some(ds => ds.data.some(v => v !== null)); $('chartEmpty').style.display = hasValues ? 'none' : 'flex';
  if (state.chart) state.chart.destroy();
  if (!window.Chart) return;
  state.chart = new Chart($('financialChart'), { type: 'bar', data: { labels, datasets: datasets.map(ds => ({ ...ds, data: ds.data.map(v => v === null ? 0 : v) })) }, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false }, tooltip: { callbacks: { label: (ctx) => `${ctx.dataset.label}: ${ctx.raw.toLocaleString()}` } } }, scales: { x: { grid: { display: false }, ticks: { color: '#8994a7', font: { size: 10 }, maxRotation: 35, minRotation: 0 } }, y: { beginAtZero: true, grid: { color: '#eef1f7' }, ticks: { color: '#8994a7', font: { size: 10 }, callback: v => Number(v).toLocaleString() } } } } });
}
function listFromRecord(record, candidates) { const val = first(record, candidates); if (Array.isArray(val)) return val.map(x => typeof x === 'string' ? x : first(x, ['text', 'description', 'factor', 'name', 'value']) || JSON.stringify(x)).filter(Boolean); if (typeof val === 'string') return val.split(/\n|\r|•/).map(s => s.trim().replace(/^[-*\d.)\s]+/, '')).filter(Boolean); return []; }
function renderInsights() {
  const r = state.records.find(x => keyOf(x) === $('insightSelect').value);
  $('growthDriversList').innerHTML = ''; $('riskFactorsList').innerHTML = '';
  $('inspectorYear');
  const groups = [[$('growthDriversList'), listFromRecord(r, ['growth_drivers', 'growthDrivers', 'growth_factors', 'growth_opportunities', 'top_growth_drivers'])], [$('riskFactorsList'), listFromRecord(r, ['risk_factors', 'riskFactors', 'top_risk_factors', 'risks'])]];
  for (const [el, items] of groups) { if (!r || !items.length) { const li = document.createElement('li'); li.className = 'muted-list-item'; li.textContent = !r ? 'Select a report to view available insights.' : 'No structured items were returned for this section in this KPI record.'; el.appendChild(li); } else for (const item of items) { const li = document.createElement('li'); li.textContent = item; el.appendChild(li); } }
}
async function loadKPIs() { try { const data = await api('/api/kpis'); if (!Array.isArray(data)) throw new Error('The KPI endpoint did not return a list.'); state.records = data; renderStats(); renderSelectors(); renderTable(); renderChart(); if (!$('insightSelect').value && state.records.length) $('insightSelect').value = keyOf(state.records[0]); renderInsights(); setApiStatus(true, 'Connected to FastAPI'); } catch (e) { $('metricsTableBody').innerHTML = `<tr><td colspan="7" class="table-empty">Could not load KPIs: ${escapeHtml(e.message)}. Check that the backend is running.</td></tr>`; setApiStatus(false, 'Backend unavailable'); showToast(`Could not load KPI records: ${e.message}`, 'error'); } }
function renderJob(job) {
  const status = String(job.status || 'processing').toLowerCase(); const progress = Math.max(0, Math.min(100, Number(job.progress ?? 0)));
  $('jobPanel').classList.remove('hidden'); $('jobStatus').textContent = status === 'completed' ? 'Report processed successfully' : status === 'failed' ? 'Ingestion failed' : `Processing ${job.company || 'report'}${job.year ? ` · ${job.year}` : ''}`;
  $('jobPercent').textContent = `${progress}%`; $('jobProgress').style.width = `${progress}%`;
  $('jobMessage').textContent = job.error || (job.current_step ? `Current step: ${job.current_step}` : status === 'completed' ? 'Your extracted data is ready.' : 'Running the ingestion pipeline…');
  const steps = Array.isArray(job.steps) ? job.steps : []; $('stepList').innerHTML = steps.map(s => { const st = String(s.status || 'pending').toLowerCase(); return `<li class="${st === 'done' ? 'done' : st === 'running' ? 'running' : ''}">${escapeHtml(s.name || s.step || 'Processing')}${st === 'done' ? ' ✓' : st === 'running' ? ' · in progress' : ''}</li>`; }).join('');
}
async function pollJob(jobId) { let elapsed = 0; const maxElapsed = 20 * 60 * 1000; while (elapsed < maxElapsed) { const job = await api(`/api/ingest/${encodeURIComponent(jobId)}`); renderJob(job); const status = String(job.status || '').toLowerCase(); if (['completed', 'failed'].includes(status)) { $('uploadBtn').disabled = false; $('uploadBtn').innerHTML = 'Upload & analyze report <span>→</span>'; if (status === 'completed') { showToast('Report ingested successfully. KPI data refreshed.', 'success'); await loadKPIs(); } else showToast(job.error || 'Report ingestion failed.', 'error'); return; } await new Promise(resolve => setTimeout(resolve, 1500)); elapsed += 1500; } throw new Error('This job is taking longer than expected. You can check its status again by refreshing the page only if you still have the job ID.'); }
async function uploadReport(event) { event.preventDefault(); const file = $('fileInput').files[0]; if (!file) return showToast('Choose a PDF file first.', 'error'); if (!file.name.toLowerCase().endsWith('.pdf')) return showToast('Only PDF files are supported.', 'error'); const form = new FormData(); form.append('file', file); if ($('companyInput').value.trim()) form.append('company', $('companyInput').value.trim()); if ($('yearInput').value.trim()) form.append('year', $('yearInput').value.trim()); $('uploadBtn').disabled = true; $('uploadBtn').textContent = 'Uploading…'; $('jobPanel').classList.remove('hidden'); $('jobStatus').textContent = 'Uploading report…'; $('jobMessage').textContent = 'Sending PDF to FastAPI.'; $('jobPercent').textContent = '—'; $('jobProgress').style.width = '8%'; $('stepList').innerHTML = ''; try { const accepted = await api('/api/ingest', { method: 'POST', body: form }); if (!accepted || !accepted.job_id) throw new Error('The API response did not include a job_id.'); renderJob({ status: accepted.status || 'queued', progress: 0, company: accepted.company, year: accepted.year, steps: [] }); await pollJob(accepted.job_id); } catch (e) { $('uploadBtn').disabled = false; $('uploadBtn').innerHTML = 'Upload & analyze report <span>→</span>'; $('jobStatus').textContent = 'Could not process upload'; $('jobMessage').textContent = e.message; $('jobProgress').style.width = '0%'; showToast(e.message, 'error'); } }
function addMessage(role, content, sources = []) { const row = document.createElement('div'); row.className = `chat-message ${role === 'user' ? 'user-message' : 'assistant-message'}`; const avatar = document.createElement('div'); avatar.className = 'message-avatar'; avatar.textContent = role === 'user' ? 'You' : '✳'; const body = document.createElement('div'); body.className = 'message-body'; const strong = document.createElement('strong'); strong.textContent = role === 'user' ? 'You' : 'AI Analyst'; const p = document.createElement('p'); p.textContent = content; body.append(strong, p); if (role !== 'user' && Array.isArray(sources) && sources.length) { const sourceBox = document.createElement('div'); sourceBox.className = 'sources'; const heading = document.createElement('strong'); heading.textContent = 'Retrieved sources'; sourceBox.appendChild(heading); sources.forEach((source, i) => { const item = document.createElement('div'); item.className = 'source-item'; if (typeof source === 'string') item.textContent = source; else { const name = first(source, ['filename', 'file_name', 'source', 'document', 'title', 'name']) || `Source ${i + 1}`; const page = first(source, ['page', 'page_number', 'pageNumber']); const snippet = first(source, ['content', 'text', 'snippet', 'excerpt']); item.textContent = `${name}${page !== '' ? ` · Page ${page}` : ''}${snippet ? ` — ${snippet}` : ''}`; } sourceBox.appendChild(item) }); body.appendChild(sourceBox); } row.append(avatar, body); $('chatMessages').appendChild(row); $('chatMessages').scrollTop = $('chatMessages').scrollHeight; }
async function sendChat(event) { event.preventDefault(); const question = $('chatInput').value.trim(); if (!question) return; const company = $('chatCompanySelect').value; const year = $('chatYearSelect').value; addMessage('user', question); $('chatInput').value = ''; $('sendBtn').disabled = true; $('sendBtn').textContent = 'Thinking…'; try { const result = await api('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question, company: company || null, year: year || null, history: state.history }) }); const answer = first(result, ['answer', 'response', 'message', 'content']) || 'The API returned no answer text.'; const sources = first(result, ['sources', 'source_documents', 'citations', 'retrieved_sources']) || []; addMessage('assistant', String(answer), sources); state.history.push({ role: 'user', content: question }, { role: 'assistant', content: String(answer) }); if (state.history.length > 12) state.history = state.history.slice(-12); } catch (e) { addMessage('assistant', `I couldn't get an answer from the backend: ${e.message}`); showToast(`Chat request failed: ${e.message}`, 'error'); } finally { $('sendBtn').disabled = false; $('sendBtn').textContent = 'Send ↗'; $('chatInput').focus(); } }
function bindEvents() { $('refreshBtn').addEventListener('click', loadKPIs); $('tableSearch').addEventListener('input', renderTable); $('reportSelect').addEventListener('change', renderChart); $('insightSelect').addEventListener('change', renderInsights); $('uploadForm').addEventListener('submit', uploadReport); $('chatForm').addEventListener('submit', sendChat); $('fileInput').addEventListener('change', () => { const f = $('fileInput').files[0]; $('fileLabel').textContent = f ? f.name : 'Drop a PDF here or browse'; if (f && !$('companyInput').value.trim()) { const m = f.name.match(/^(\d{4})[_ -](.+)\.pdf$/i); if (m) { $('yearInput').value = $('yearInput').value || m[1]; $('companyInput').value = m[2].replace(/[_-]+/g, ' '); } } }); const drop = $('dropzone'); for (const ev of ['dragenter', 'dragover']) drop.addEventListener(ev, e => { e.preventDefault(); drop.classList.add('dragover') }); for (const ev of ['dragleave', 'drop']) drop.addEventListener(ev, e => { e.preventDefault(); drop.classList.remove('dragover') }); drop.addEventListener('drop', e => { const file = e.dataTransfer.files[0]; if (file) { const transfer = new DataTransfer(); transfer.items.add(file); $('fileInput').files = transfer.files; $('fileInput').dispatchEvent(new Event('change')); } }); document.querySelectorAll('.nav-link').forEach(link => link.addEventListener('click', () => { document.querySelectorAll('.nav-link').forEach(n => n.classList.remove('active')); link.classList.add('active') })); }
document.addEventListener('DOMContentLoaded', () => { bindEvents(); checkHealth(); loadKPIs(); });
